# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='', help_text='编号', max_length=10)),
                ('name', models.CharField(default='', help_text='姓名', max_length=10)),
                ('contact', models.CharField(default='', help_text='姓名', max_length=10)),
                ('mac', models.CharField(default='', help_text='姓名', max_length=20)),
                ('ip', models.CharField(default='', help_text='姓名', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='', help_text='编号', max_length=10)),
                ('person_id', models.IntegerField(help_text='使用者ID')),
                ('position', models.CharField(default='', help_text='所在位置', max_length=50)),
                ('system_os', models.CharField(default='', help_text='操作系统', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='鲁大师评分')),
                ('cpu', models.CharField(default='', help_text='CPU', max_length=50)),
                ('memory', models.CharField(default='', help_text='CPU', max_length=50)),
                ('pc_description', models.TextField(default='', help_text='PC详细描述')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='启用时间')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='姓名', max_length=10)),
                ('position', models.CharField(default='', help_text='所在位置', max_length=50)),
                ('contact', models.CharField(default='', help_text='联系方式', max_length=50)),
                ('pc_mac', models.CharField(default='', help_text='MAC', max_length=20)),
                ('pc_ip', models.CharField(default='', help_text='IP4', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='', help_text='编号', max_length=10)),
                ('person_id', models.IntegerField(help_text='使用者ID')),
                ('position', models.CharField(default='', help_text='所在位置', max_length=50)),
                ('prt_model', models.CharField(default='', help_text='打印机型号', max_length=50)),
                ('prt_description', models.TextField(default='', help_text='打印机详细描述')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='启用时间')),
            ],
        ),
    ]
