# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareinfo',
            old_name='cpu',
            new_name='pc_cpu',
        ),
        migrations.RenameField(
            model_name='hardwareinfo',
            old_name='memory',
            new_name='pc_memory',
        ),
        migrations.RenameField(
            model_name='hardwareinfo',
            old_name='score',
            new_name='pc_score',
        ),
    ]
