# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160622_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwareinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='printerinfo',
            name='create_time',
        ),
        migrations.AddField(
            model_name='hardwareinfo',
            name='use_time',
            field=models.DateTimeField(blank=True, help_text='启用时间', null=True),
        ),
        migrations.AddField(
            model_name='printerinfo',
            name='use_time',
            field=models.DateTimeField(blank=True, help_text='启用时间', null=True),
        ),
    ]
