# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160622_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='mac',
        ),
        migrations.AddField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 22, 11, 45, 23, 956803, tzinfo=utc), help_text='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changelog',
            name='remark',
            field=models.TextField(default='', help_text='变更说明'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='type',
            field=models.CharField(default='', help_text='变更类型', max_length=10),
        ),
    ]
