# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160622_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_ip', models.CharField(default='', help_text='IP4', max_length=20)),
                ('img_number', models.IntegerField(help_text='图片编号')),
            ],
        ),
    ]
