# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160630_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 30, 18, 16, 21, 522207), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='remark',
            field=models.TextField(default='', verbose_name='变更说明'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='serial_number',
            field=models.CharField(default='', max_length=10, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='type',
            field=models.CharField(default='', max_length=10, verbose_name='变更类型'),
        ),
    ]
