# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160630_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 9, 31, 49, 754900), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='pc_cpu',
            field=models.CharField(default='', max_length=50, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='pc_description',
            field=models.TextField(default='', verbose_name='PC详细描述'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='pc_memory',
            field=models.CharField(default='', max_length=50, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='pc_score',
            field=models.IntegerField(default=0, verbose_name='鲁大师评分'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='person_id',
            field=models.IntegerField(verbose_name='使用者ID'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='position',
            field=models.CharField(default='', max_length=50, verbose_name='所在位置'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='serial_number',
            field=models.CharField(default='', max_length=10, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='system_os',
            field=models.CharField(default='', max_length=20, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='use_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='启用时间'),
        ),
        migrations.AlterField(
            model_name='likeimageinfo',
            name='img_number',
            field=models.IntegerField(default=0, verbose_name='图片编号'),
        ),
        migrations.AlterField(
            model_name='likeimageinfo',
            name='pc_ip',
            field=models.CharField(default='', max_length=20, verbose_name='IP4'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='contact',
            field=models.CharField(default='', max_length=50, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='pc_ip',
            field=models.CharField(default='', max_length=20, verbose_name='IP4'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='pc_mac',
            field=models.CharField(default='', max_length=20, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='position',
            field=models.CharField(default='', max_length=50, verbose_name='所在位置'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='person_id',
            field=models.IntegerField(verbose_name='使用者ID'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='position',
            field=models.CharField(default='', max_length=50, verbose_name='所在位置'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='prt_description',
            field=models.TextField(default='', verbose_name='打印机详细描述'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='prt_model',
            field=models.CharField(default='', max_length=50, verbose_name='打印机型号'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='serial_number',
            field=models.CharField(default='', max_length=10, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='use_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='启用时间'),
        ),
    ]
