# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160701_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 10, 37, 0, 798900), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='pc_memory',
            field=models.CharField(default='', max_length=50, verbose_name='内存'),
        ),
    ]
