# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160701_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 10, 51, 37, 580900), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='system_os',
            field=models.CharField(default='', max_length=100, verbose_name='操作系统'),
        ),
    ]
