# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160701_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 15, 31, 56, 910400), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='pc_description',
            field=models.TextField(blank=True, default='', verbose_name='PC详细描述'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='prt_description',
            field=models.TextField(blank=True, default='', verbose_name='打印机详细描述'),
        ),
    ]
