# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160701_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareinfo',
            name='pc_ip',
            field=models.CharField(default='', max_length=20, verbose_name='IP4'),
        ),
        migrations.AddField(
            model_name='hardwareinfo',
            name='pc_mac',
            field=models.CharField(default='', max_length=20, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 5, 14, 52, 24, 416250), verbose_name='创建时间'),
        ),
    ]
