# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160705_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 7, 18, 20, 9, 687546), verbose_name='创建时间'),
        ),
    ]
