# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160707_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 8, 14, 40, 30, 191528), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hardwareinfo',
            name='serial_number',
            field=models.CharField(default='', max_length=20, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='printerinfo',
            name='serial_number',
            field=models.CharField(default='', max_length=20, verbose_name='编号'),
        ),
    ]
